# Generated by Django 5.2.1 on 2025-06-22 04:21

import django.db.models.deletion
import systems.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributor", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                ("config", systems.models.fields.DictionaryField(default=dict)),
                ("provider_type", models.CharField(default="base", max_length=128)),
                (
                    "variables",
                    systems.models.fields.DictionaryField(default=dict, editable=False),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "external_id",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("description", models.TextField(default=None, null=True)),
                ("remote", models.CharField(default="origin", max_length=128)),
                ("url", models.URLField(default=None, max_length=256, null=True)),
                ("topics", systems.models.fields.ListField(default=list)),
                ("default_branch", models.CharField(default="main", max_length=256)),
                ("git_url", models.URLField(default=None, max_length=256, null=True)),
                ("private", models.BooleanField(default=None, null=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="contributor.contributor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository",
                "verbose_name_plural": "repositories",
                "db_table": "factory_repository",
                "ordering": ["id"],
                "abstract": False,
                "unique_together": {("organization", "name")},
            },
        ),
    ]
