# Generated by Django 5.2.1 on 2025-06-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={
                "ordering": ["name"],
                "verbose_name": "repository",
                "verbose_name_plural": "repositories",
            },
        ),
    ]
