# Generated by Django 5.2.1 on 2025-06-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_alter_repository_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="contributor",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="remote",
        ),
    ]
