# Generated by Django 5.2.1 on 2025-06-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributor", "0001_initial"),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "external_id",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                ("url", models.URLField(default=None, max_length=256, null=True)),
                ("text", models.TextField(default=None, null=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="contributor.contributor",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="issue.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "factory_comment",
                "ordering": ["external_id"],
                "abstract": False,
                "unique_together": {("issue", "external_id")},
            },
        ),
    ]
