# Generated by Django 5.2.1 on 2025-06-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
