# Generated by Django 5.2.1 on 2025-06-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequestComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="comment.comment",
                    ),
                ),
                ("path", models.CharField(default=None, max_length=512, null=True)),
                ("line", models.IntegerField(default=None, null=True)),
                ("position", models.IntegerField(default=None, null=True)),
            ],
            options={
                "verbose_name": "pull request comment",
                "verbose_name_plural": "pull request comments",
                "db_table": "factory_pull_request_comment",
                "ordering": ["external_id"],
                "abstract": False,
            },
            bases=("comment.comment",),
        ),
    ]
