# Generated by Django 5.2.1 on 2025-06-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributor", "0001_initial"),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "issue_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="issue.issue",
                    ),
                ),
                ("issue_url", models.URLField(default=None, max_length=256, null=True)),
                (
                    "base_branch",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                (
                    "head_branch",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="contributor.contributor"
                    ),
                ),
            ],
            options={
                "verbose_name": "pull request",
                "verbose_name_plural": "pull requests",
                "db_table": "factory_pull_request",
                "ordering": ["id"],
                "abstract": False,
            },
            bases=("issue.issue",),
        ),
    ]
