# Generated by Django 5.2.1 on 2025-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributor", "0001_initial"),
        ("pull_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pullrequest",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="pull_requests", to="contributor.contributor"
            ),
        ),
    ]
