# Generated by Django 5.2.1 on 2025-06-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pull_request", "0002_alter_pullrequest_reviewers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pullrequest",
            options={
                "ordering": ["external_id"],
                "verbose_name": "pull request",
                "verbose_name_plural": "pull requests",
            },
        ),
    ]
