_base_model: &base_model
    base: id_resource
    admin_roles: [dev-team]
    view_roles: [dev-team]
    priority: 100

roles:
    dev-team: "Development Team"

models:
    organization:
        <<: *base_model
        base: name_resource
        display: "<name>"
        plugin: true
        default_provider: github
        key: name
        fields:
            full_name:
                type: string
                options:
                    max_length: 256
            url:
                type: url

    contributor:
        <<: *base_model
        display: "<provider>:<name>"
        id_fields: [provider, name]
        key: id
        fields:
            provider:
                type: string
                options:
                    max_length: 256
            url:
                type: url

    repository:
        <<: *base_model
        base: organization
        plural: repositories
        display: "<organization_id>/<name>"
        plugin: true
        default_provider: github
        id_fields: [organization, name]
        key: name
        fields:
            external_id:
                type: string
                options:
                    max_length: 128
            description:
                type: text
            private:
                type: boolean
            url:
                type: url
            git_url:
                type: url
            default_branch:
                type: string
                options:
                    max_length: 256
                    default: main
            topics:
                type: list

    issue:
        <<: *base_model
        base: repository
        mixins: [contributor]
        display: "<repository_id>:<external_id>"
        plugin: true
        default_provider: github
        id_fields: [repository, external_id]
        key: external_id
        fields:
            external_id:
                type: string
            number:
                type: integer
            text:
                type: text
            state:
                type: string
                options:
                    max_length: 128
            locked:
                type: boolean
            assignees:
                type: many_to_many
                options:
                    related_data_name: contributor
                    reverse_related_name: "issues"
            url:
                type: url
            labels:
                type: list

    comment:
        <<: *base_model
        base: issue
        data_mixins: [contributor]
        id_fields: [issue, external_id]
        key: external_id
        display: "<issue_id>:<external_id>"
        name_field: false
        fields:
            external_id:
                type: string
            text:
                type: text
            url:
                type: url

    pull_request:
        <<: *base_model
        base: issue
        extend: true
        display: "<repository_id>:<external_id>"
        id_fields: [repository, external_id]
        key: external_id
        fields:
            issue_url:
                type: url
            base_branch:
                type: string
                options:
                    max_length: 256
            head_branch:
                type: string
                options:
                    max_length: 256
            reviewers:
                type: many_to_many
                options:
                    related_data_name: contributor
                    reverse_related_name: "pull_requests"

    pull_request_comment:
        <<: *base_model
        base: comment
        extend: true
        display: "<issue_id>:<external_id>"
        id_fields: [issue, external_id]
        key: external_id
        fields:
            path:
                type: string
                options:
                    max_length: 512
            line:
                type: integer
            position:
                type: integer
