# Generated by Django 5.2.1 on 2025-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "full_name",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                ("url", models.URLField(default=None, max_length=256, null=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "db_table": "factory_organization",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
