# Generated by Django 5.2.1 on 2025-06-22 04:21

import django.db.models.deletion
import systems.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributor", "0001_initial"),
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("text", models.TextField(default=None, null=True)),
                ("state", models.CharField(default=None, max_length=128, null=True)),
                (
                    "external_id",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                ("url", models.URLField(default=None, max_length=256, null=True)),
                ("locked", models.BooleanField(default=None, null=True)),
                ("topics", systems.models.fields.ListField(default=list)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="contributor.contributor"
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="contributor.contributor",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(data_name)s",
                        to="repository.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "db_table": "factory_issue",
                "ordering": ["external_id"],
                "abstract": False,
                "unique_together": {("repository", "external_id")},
            },
        ),
    ]
