# Generated by Django 5.2.1 on 2025-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributor", "0001_initial"),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="issues", to="contributor.contributor"
            ),
        ),
    ]
