# Generated by Django 5.2.1 on 2025-06-25 09:23

import systems.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0002_alter_issue_assignees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="topics",
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=systems.models.fields.ListField(default=list),
        ),
        migrations.AddField(
            model_name="issue",
            name="type",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
