# Generated by Django 5.2.1 on 2025-06-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0003_remove_issue_topics_issue_labels_issue_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="type",
        ),
    ]
