# Generated by Django 5.2.1 on 2025-06-26 17:56

import systems.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0004_remove_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="config",
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AddField(
            model_name="issue",
            name="provider_type",
            field=models.CharField(default="base", max_length=128),
        ),
        migrations.AddField(
            model_name="issue",
            name="variables",
            field=systems.models.fields.DictionaryField(default=dict, editable=False),
        ),
    ]
