# Generated by Django 5.2.1 on 2025-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0005_issue_config_issue_provider_type_issue_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="number",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
