# Generated by Django 5.2.1 on 2025-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0006_issue_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="type",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
